{% set version = "1.3.3" %}

package:
  name: hachoir-core
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/hachoir-core/hachoir-core-{{ version }}.tar.gz
  sha256: ecf5d16eccc76b22071d6062e54edb67595f70d827644d3a6dff04289b4058df


build:
  noarch: python
  number: 2
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python <3
    - pip
  run:
    - python <3

test:
  imports:
    - hachoir_core
    - hachoir_core.field
    - hachoir_core.stream

about:
  home: http://bitbucket.org/haypo/hachoir/wiki/hachoir-core
  license: GPL 2.0
  license_file: COPYING
  summary: 'Core of Hachoir framework: parse and edit binary files'

extra:
  recipe-maintainers:
    - pmlandwehr
