travis:
  secure:
    BINSTAR_TOKEN: mYOlZ/3DGFUzqesFfWdTcVXTg1fTp3gzKVzSGaSeC8gnJVJ68A3HxZj/bnNcJHdD5ZmwcuBJwtXB+GdVuwGQ+kuDLxoFNLrjPz+kxWaZKFajUvJNzGnGjmrk02Sz0pfT8mI3ZOhmZF2iKIFJVmPtM66uChsoN67DtLncqnwOUWzhDvgLrt7VyP6K5d9SsuY+Hg0u4s03+8D1nlUghopj4Nu/hoBPfZLIzl4Lc4h3wqo8HjJEjrzXr8FEYVDiglm1nSvwhBhJwfz1L68V27Hpio2r9F1dHKBeWIzuiv9ohOudAgIiWDEEx70PkumN7NeMgTmv44iZmBXEklY3AA1TCNHoU9s+ZvTI5zND2VSiXcMQTZMU4I2Am+OXazyIedr46DPesD/x5tvL/y8TIFSxx3J4uCFpETor6iu+0yDSdFX+XrKJyYAPqR9GnCvHzzW9lmc4JpqG9nlospss2W8iv4kl+nsWe3Bm9wTPU3gfe/PJlx6CB0VECJ01YUKogrtjVBFWLrZRG71Fdtc7P0nSPW/iCoSKuqIF4VRFzisH2h+KZUX8uZvFzKu8nu5Qdk+3wUUFkVTu645dTMvNLmZCzk2AhvfRm6eLVjWxhil2Z+nYj0xP18ZDcsv6f0467Qy8Q2WOTaj2IquHAwfQxaTvtqJwr6xpNY3wi/MVak2pYOc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
