travis:
  secure:
    BINSTAR_TOKEN: QtmI5jC845TodJfKc4VT3GUdul4uR932GmRX9ggsoG0DkhTP4BCbcCy+FpHyr3pXJsVh1EpOYfGWJGHpwonkcfbzbugKssGyanauHrLjAjf+9UjMbOeYbAdZtcqUGqSxkQVmjFlGalZWlKxi3AmsE9o172ByLYX2JJ99Cip4fba3/cghvw9BCthS1hh2KgeVE35YBjBiWXC80YPY7biZ8EmS3drief1cfTKoZBm+V8CUc9ei6mqPcqOjsYXnFzrpHwHlDaPK7f1iI18g01sur0kx3C359SQVvymXfVIVcUzIpIzvqS65gRESbTY2rXdpEjOMsAsGaPSFNiWg7H/QigMF3AbCvDR1mznh7xQY9aA1q6yFm82DPUz3/JKU5AMmw8XQrFqk1RaPqJIHo4LX939P8Qfawnl7CoQ6LymDCsu+mBpoHHnxY2o/sxWMzzBzUAzdsJMCW08hX0DsZmkwaW46NtcUjM1NhlePfhnpSWdzIZfqQIXpmfylO5etQG2RmWZZj6/6dHChA7GEHfsoJ/W2Dz0amuuesDfpPxiPbh4MEP8DT4f0bhMlI+2N4dE2K0ABm515numPWDie0jm6DPff1Zw6wubJ7TL3JO4UCUl/wymMYmrm8naGRcCB8Q36GjQ7cAyDnJ4dgVURn6S4MDAaem/aOAzFeSKniIvUjxo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
